name: build-playground/integration-tests/yaml/download_steps
on:
  push:
    branches:
    - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      if: true
      with:
        name: WebApp
#     # This action relies on the workflow '.yml' being present in this repository (change the repository parameter if the workflow is in a different repository).
#     # Ensure the workflow exists and uploads an artifact for this to use.
#     - uses: dawidd6/action-download-artifact@v2
#       with:
#         github_token: "${{ secrets.GITHUB_TOKEN }}"
#         repo: "${{ github.repository }}"
