name: build-playground/joel.dunham/VariableTemplates
on: push
env:
  favoriteVeggie: brussels sprouts
  message: from pipeline
  spam: eggs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: echo My favorite vegetable is ${{ variables.favoriteVeggie }}.
    - run: echo My favorite breakfast is ${{ variables.spam }}
    - run: echo ${{ variables.message }}
